name: Build Docker Image

# Trigger the workflow on pushes to the main branch or on pull requests
on:
  push:
    branches:
      main
  pull_request:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile.chailab'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.chailab
        tags: temp-image:latest
        push: false